#!/bin/sh
export LANG=ru_RU.UTF-8
if command -v box64 >/dev/null; then
    BOX64_NOBANNER=1 BOX64_LD_LIBRARY_PATH=~/box64/x64lib BOX64_RCFILE=~/box64/system/box64.box64rc exec ~/box64/build/box64 "$HOME/wine/bin/$(basename "$0")" "$@"
else
    BOX86_NOBANNER=1 BOX86_LD_LIBRARY_PATH=~/box86/x86lib BOX86_RCFILE=~/box86/system/box86.box86rc WINEPREFIX=~/.wine32 exec ~/box86/build/box86 "$HOME/wine32/bin/$(basename "$0")" "$@"
fi
